### DISCUSSION TITLE
Create a pre-commit hook.

### DISCUSSION THREAD

**Discussion by veritas9872** [rome/tools#4246] [Suggestions]
I am very impressed by the Rome project and I would like to suggest creating a pre-commit hook or a mirror to host that hook.
This would be a very simple modification that would greatly improve the usability of the Rome project.
Currently, the only reason that many people, including myself, stay with prettier is the lack of pre-commit support in Rome.

**Comment by ematipico** [comment]
I don't think Rome will provide such functionality, at least in the near future.

BTW, neither Prettier supports git hooks out of the box, in fact in their website they provide some alternatives on **how to set it up**: https://prettier.io/docs/en/precommit.html#docsNav

You could try to set up Rome using this guide and using the appropriate arguments for the CLI.

**Comment by Th3S4mur41** [comment]
An easy solution to this is using a combination of [husky](https://typicode.github.io/husky) and [lint-staged](https://github.com/okonet/lint-staged)...
Then adding a pre-commit hook in husky that just runs `npx lint-staged` with the following *.lintstagedrc.json*

```json
{
	"**/*.{js,cjs,mjs,ts}": ["rome format --write", "rome check"]
}
```

Speed is quite good compared to the prettier/eslint combination 🏎️

The lint-staged config could even be simplified with a [--ignore-unknown option](https://github.com/rome/tools/discussions/4267)

**Reply by ematipico** [reply]
FYI, the next version will have that option https://github.com/rome/tools/pull/4547

**Comment by JayOfferdahl** [comment]
@veritas9872: I was adding Rome to one of my projects and wanted this functionality. ~~I stood up a mirror here: https://github.com/JayOfferdahl/mirrors-rome~~

LMK if this works for you!

Update: This can be easily accomplished using a local node repo as follows:

```
    - repo: local
      hooks:
          - id: rome
            entry: rome
            name: rome
            args: [check]
            language: node
            types_or: [javascript, ts, jsx, tsx, json]
            additional_dependencies:
                - rome
```
