### ISSUE TITLE
Proposal: CST-like Bogus AST Nodes

### ISSUE THREAD

**Issue by jamiebuilds** [rome/tools#1848]
### Description

> **Note:** I'm using "bogus" instead of "unknown" (See #1819)

CST nodes have a lot of qualities that make it nice to represent both errors and error recovery.

Take the following code:

```js
function %error% foo() {}
```

It should look something like this in CST form:

```yaml
JsProgram:
  - JsFunctionStatement:
    - "function"
    - unexpected: "%error%"
    - JsIdentifierBinding: ["foo"]
    - JsParameterList: ["(", ")"]
    - JsFunctionBody: ["{", "}"]
```

We can tell a few things from this:

- We've inferred that this is a `JsFunctionStatement` even though it contains errors.
- We've recovered from the error by _guessing_ that `foo` is the identifier.

Just as easily we could have created this CST:

```yaml
JsProgram:
  - JsFunctionStatement:
    - "function"
    - unexpected: "%"
    - JsIdentifierBinding: ["error"]
    - unexpected: "% foo"
    - JsParameterList: ["(", ")"]
    - JsFunctionBody: ["{", "}"]
```

Or this one:

```yaml
JsProgram:
  - JsFunctionStatement:
    - "function"
    - unexpected: "%error% foo() {}"
```

Or this one:

```yaml
JsProgram:
  - unexpected: "function %error% foo() {}"
```

It that sense, the CST is a very clear representation of how our error recovery works, and it provides a lot of flexibility for us to improve.

But we throw all that out as soon as we're using the AST.

In our current design we have a limited set of "Bogus" (Unknown) nodes where we can say an error exists. But it doesn't provide us the flexibility to recover inside of the node. It also forces us to pretend an error is more wide-spread than it really _should_ be.

```rs
JsProgram:
  - BogusJsStatement
```

But what if we made these bogus nodes more CST-like?

```rs
BogusJsStatement {
  kind: JsFunctionStatement,
  children: Vec<Node | Token | Error>,
}
```

This provides us with all of the flexibility of the CST:

```rs
// Give up immediately:
BogusJsStatement {
  kind: JsFunctionStatement,
  children: [
    JsFunctionKeyword("function"),
    Unexpected("%error% foo() {}"),
  ],
}

// Don't assume the foo is a JsIdentifierBinding:
BogusJsStatement {
  kind: JsFunctionStatement,
  children: [
    JsFunctionKeyword("function"),
    Unexpected("%error% foo"),
    JsParameterList(paren_open: "(", list: List(), paren_close: ")"),
    JsFunctionBody(brace_open: "{", brace_close: "}")
  ],
}

// Assume the foo is a JsIdentifierBinding:
BogusJsStatement {
  kind: JsFunctionStatement,
  children: [
    JsFunctionKeyword("function"),
    JsUnexpected("%error%"),
    IdentifierBinding(text: "foo"),
    JsParameterList(paren_open: "(", list: List(), paren_close: ")"),
    JsFunctionBody(brace_open: "{", brace_close: "}")
  ],
}
```

## AST navigation

Let's take this AST:

```rs
JsProgram {
  items: [
    BogusJsStatement {
      kind: JsFunctionStatement,
      children: [
        JsFunctionKeyword("function"),
        JsUnexpected("%error%"),
        IdentifierBinding(text: "foo"),
        JsParameterList(paren_open: "(", list: List(), paren_close: ")"),
        JsFunctionBody(brace_open: "{", brace_close: "}")
      ],
    }
  ]
}
```

There are a number of different operations an analyzer could run on this:

```rs
find_a_node::<JsScript>() // Some(JsScript)
find_a_node::<JsScript>()?.items() // Iterator(AnyJsStatement)
find_a_node::<JsScript>()?.items().get(0) // Some(AnyJsStatement)
find_a_node::<JsScript>()?.items().get(0)?.cast::<JsFunctionStatement>() // Err(BogusJsStatement)
find_a_node::<JsScript>()?.items().get(0)?.cast::<BogusJsStatement>() // Ok(BogusJsStatement)
find_a_node::<JsFunctionStatement>() // None
find_a_node::<BogusJsStatement>() // Some(BogusJsStatement)
find_a_node::<JsFunctionBody>() // Some(JsFunctionBody)
```

To summarize:

- You can't visit the "function statement" because it doesn't exist, just a "bogus statement" we inferred was a function statement.
- You can visit the nodes inside the "bogus statement" because we recovered them.
- You can still access the `BogusJsStatement`.

While I think you should be able to access the `BogusJsStatement`, I don't think it should give you access to its children.

My biggest concern is that analyzers, particularly third-party ones, would eventually end up depending on indexes of the `BogusJsStatement` and it would make every change to our error recovery a breaking change.

Luckily, Rust allows us to make it so that those indexes are not a public API:

```rs
impl BogusJsStatement {
  pub(crate) fn children();
}
```

However, we should consider what types we return for child nodes trying to reach back up the tree into the bogus node.

```rs
find_a_node::<JsFunctionBody>().parent() // ???
```

`FunctionBody::parent()` could return any of:

- `AnyJsNode`
- `Result<AnyJsNode, AnyBogusJsNode>`
- `AnyJsFunction | AnyBogusJsNode`
- `Some(AnyJsFunction)` 

I'm not sure which is the best choice, but the last two of those would require
us to codegen `.parent()` methods everywhere.
