### ISSUE TITLE
🐛 Helix editor: Rome language server shadows TS

### ISSUE THREAD

**Issue by arendjr** [rome/tools#4107]
### Environment information

```block
I’m trying to set up the Rome Language Server with the Helix editor. While everything seems to work at first glance, I notice that functionality offered by the TypeScript language server, such as “goto definition” is no longer available.
```

### What happened?

I installed the Helix editor and followed the instructions for configuring the Rome language server: https://github.com/rome/tools/blob/main/editors/helix/manual.md

While the Rome language server now works, it had the unintended side-effect of making functionality from TypeScript language server unavailable.

### Expected result

Both functionality from the Rome language server and the TypeScript language server should be available.

Maybe the Rome language server should forward commands it doesn’t handle to the TS language server? I did confirm that `typescript-language-server` was in my `PATH` when I ran `rome start`.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by rchl** [comment]
Rome doesn't advertise that it is a `definitionProvider` so related functionality should not be affected. I would suggest reporting it against the Helix editor.

**Comment by arendjr** [comment]
I reported the issue with the Helix editor and it seems a PR is already open on their side to add support for multiple language servers per language. If you don’t mind, we can keep this issue open and I’ll create a PR to update your Helix config instructions once that’s merged.

**Comment by matthewmturner** [comment]
@arendjr any chance you could update helix config instructions as you mentioned above?

**Comment by arendjr** [comment]
It might require some updating, since I think they changed some things before they merged that PR. But yeah, I’ll try to give it a go over the next week.

**Comment by vedkothavade** [comment]
I was able to get the LSP linting to work, but could not get formatting -- I think it's held up by https://github.com/helix-editor/helix/pull/5626, but if this is the case, I'm not sure how the manual demo works.

This is what I have so far:
```toml
[language-server.rome]
command = "rome"
args = ["lsp-proxy"]
formatter = { command = "rome", args = ["format", "--stdin-file-path", "test.js"]}

[[language]]
language-servers = [  "rome", { name = "typescript-language-server", except-features = [ "format" ] }]
name = "javascript"
auto-format = true
```

If anyone happens to know how to fix formatting, that would be appreciated!

**Comment by wornut** [comment]
I am attempting to configure the Helix editor with multiple Language Server Protocols (LSPs) for the latest version of NextJS. I anticipate that this setup will support both linting and formatting features.

To reproduce this setup:

1. Build the Helix editor from source (master branch) to version 23.05 (b4fe31ca). This version supports multiple LSPs.
2. Rome 12.1.3

For the project languages setup, create a `languages.toml` file in the `.helix` directory with the following configuration:

```toml
[language-server.rome]
command = "node_modules/.bin/rome"
args = ["lsp-proxy"]
formatter = { command = "node_modules/.bin/rome", args = ["format", "--stdin-file-path", "test.tsx"] }

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "rome", only-features = ["format", "completion", "code-action", "diagnostics", "inlay-hints"] }, "typescript-language-server" ]
```

Following these steps, everything should function correctly. I've checked the Helix log and the Rome rage log, and both appear to be free of errors.
