### ISSUE TITLE
📎 Use the workspace to define internal crate dependencies

### ISSUE THREAD

**Issue by ematipico** [rome/tools#4510]
### Description

At the moment, in our workspace, we have internal crates that depend on others like this:

https://github.com/rome/tools/blob/1837190357aaed1a489b0c201f2b834fa187beb8/crates/rome_js_parser/Cargo.toml#L14-L20

These lines are repeated across all the `Cargo.toml`. This is not maintainable when we need to update the version numbers, for example.

We want to change this by doing the following:
- move all these definitions inside the main [`Cargo.toml`](https://github.com/rome/tools/blob/main/Cargo.toml#L26), at the root of the workspace, below `[workspace.dependencies]`
```toml
[workspace.dependencies]
 rome_js_syntax = { version = "0.0.1", path = "./crates/rome_js_syntax" } 
```
- then, change all the occurrences of our internal `rome_` creates in the various `Cargo.toml`, like this:
```diff
rome_js_syntax.workspace = true
```
